Vagrant.configure("2") do |config|
  config.vm.guest = :freebsd

  config.vm.box = "freebsd/FreeBSD-11.1-RELEASE"
  config.vm.box_version = "2017.07.21"

  # Necessary for official FreeBSD images
  config.ssh.shell = "sh"

  config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true
  config.vm.boot_timeout = 600

  config.vm.base_mac = "080027D14C66"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
    vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
  end

  config.vm.provision "file", source: "../scripts/jenkins-slave", destination: "/tmp/slave.sh"
  config.vm.provision "file", source: "../scripts/remoting-3.1.jar", destination: "/tmp/slave.jar"
  # config.vm.provision "shell", inline: "mkdir -p /usr/share/jenkins &&  mv /tmp/slave.jar /usr/share/jenkins && mv /tmp/jenkins-slave /usr/share/jenkins/jenkins-slave"


  # config.vm.provision "file", source: "../scripts/bootstrap.sh", destination: "/tmp/bootstrap.sh"
  config.vm.provision "shell", path: "../scripts/bootstrap.sh"
end
